version: '3.8'

networks:
  skck-network:


services:

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - gateway-db
    networks:
      - skck-network
